server:
  port: 8082

spring:
  application:
    name: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  security:
    passport:
      secret: ABCDEFGHIJKLMN1234567890ABCDEFGHIJKLMN1234567890