server:
  port: 8888

spring:
  application:
    name: auth-service
  session:
    store-type: jdbc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  security:
    passport:
      secret: ABCDEFGHIJKLMN1234567890ABCDEFGHIJKLMN1234567890
      expire: 60000

