server:
  port: 8888

spring:
  application:
    name: auth-service
  session:
    store-type: jdbc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  security:
    secret: d602667f3493e001490c8cd7aafe4a67a7e4ad846ae11ebc9f57380314aeec294b25af55e4227e1369018bc96d1742dc9f739e8a593129dfcd66a3ab7ecff896
    access-token:
      expire: 360000
    refresh-token:
      expire: 720000

    passport:
      secret: ABCDEFGHIJKLMN1234567890ABCDEFGHIJKLMN1234567890
      expire: 60000

