server:
  port: 8081

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: debug

app:
  security:
    passport:
      secret: ABCDEFGHIJKLMN1234567890ABCDEFGHIJKLMN1234567890
  services:
    payment:
      url: http://PAYMENT-SERVICE
    product:
      url: http://PRODUCT-SERVICE
